new test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,5 +1,3 @@
-# This is a basic workflow to help you get started with Actions
-
 name: Selenium TestNG Tests
 
 on:
@@ -14,74 +12,48 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - uses: actions/checkout@v2.5.0
 
-    - uses: actions/checkout@v2.5.0
+      - name: Set up JDK 1.8
+        uses: actions/setup-java@v2.4.0
+        with:
+          java-version: '8'
+          distribution: 'adopt'
 
+      - name: Install Chrome
+        run: |
+          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+          sudo dpkg -i google-chrome-stable_current_amd64.deb
+          sudo apt-get -f install
 
-    - name: Set up JDK 1.8
-      uses: actions/setup-java@v2.4.0
-      with:
-        java-version: '8'
-        distribution: 'adopt'
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
 
-    - name: Install Chrome
-      run: |
-        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
-        sudo dpkg -i google-chrome-stable_current_amd64.deb
-        sudo apt-get -f install
+      - name: Test with Maven and Capture Results
+        run: |
+          set +e
+          mvn test
+          TEST_EXIT_CODE=$?
+          set -e
 
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
+          # Save screenshots if tests failed
+          if [ $TEST_EXIT_CODE -ne 0 ]; then
+            mkdir -p $HOME/screenshots
+            cp -R build/reports/tests* $HOME/screenshots/
+          fi
 
-      # Save screenshots if tests failed
-    - name: Archive screenshots
-      if: failure()
-      uses: actions/upload-artifact@v2.2.4
-      with:
-        name: test
-        path: /home/runner/work/project1/project1/build/reports/tests*
+          exit $TEST_EXIT_CODE
 
-    - name: Archive artifact
-      uses: actions/upload-artifact@v2.2.4
-      with:
-        name: emailable-report.html
-        path: target/surefire-reports/emailable-report.html
+      - name: Archive screenshots
+        if: always() # Always execute this step, even if the previous step fails
+        uses: actions/upload-artifact@v2.2.4
+        with:
+          name: test
+          path: $HOME/screenshots/
 
-    - name: Test with Maven
-      run: mvn test
-
-
-# name: CI
-
-# # Controls when the workflow will run
-# on:
-#   # Triggers the workflow on push or pull request events but only for the "master" branch
-#   push:
-#     branches: [ "master" ]
-#   pull_request:
-#     branches: [ "master" ]
-
-#   # Allows you to run this workflow manually from the Actions tab
-#   workflow_dispatch:
-
-# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
-# jobs:
-#   # This workflow contains a single job called "build"
-#   build:
-#     # The type of runner that the job will run on
-#     runs-on: ubuntu-latest
-
-#     # Steps represent a sequence of tasks that will be executed as part of the job
-#     steps:
-#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-#       - uses: actions/checkout@v3
-
-#       # Runs a single command using the runners shell
-#       - name: Run a one-line script
-#         run: echo Hello, world!
-
-#       # Runs a set of commands using the runners shell
-#       - name: Run a multi-line script
-#         run: |
-#           echo Add other actions to build,
-#           echo test, and deploy your project.
+      - name: Archive artifact
+        if: always() # Always execute this step, even if the previous step fails
+        uses: actions/upload-artifact@v2.2.4
+        with:
+          name: emailable-report.html
+          path: target/surefire-reports/emailable-report.html
